# Generated by Django 2.1 on 2019-03-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190227_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date',)},
        ),
    ]
